--DATE：2019-3-5 谢龙 第五章SQL
SELECT * FROM PRODUCTS_TBL;

DROP TABLE "HR"."products_tmp";

--一开始没有表
SELECT * FROM PRODUCTS_TMP;

--建表
CREATE TABLE products_tmp
  (
    "PROD_ID"   VARCHAR2(10 BYTE) NOT NULL ENABLE,
    "PROD_DESC" VARCHAR2(40 BYTE) NOT NULL ENABLE,
    "COST"      NUMBER(6,2) NOT NULL ENABLE,
    PRIMARY KEY ("PROD_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "USERS" ENABLE
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "USERS" ;
--插入PRODUCTS_TBL全部数据
INSERT INTO PRODUCTS_TMP SELECT * FROM PRODUCTS_TBL ;
--看到了数据
SELECT * FROM PRODUCTS_TMP;

----插入空值
  INSERT INTO ORDERS_TBL (ORD_NUM, CUST_ID, PROD_ID, QTY, ORD_DATE) VALUES ('23A16','109', '7725',2, NULL);
  
COMMIT;
 
 
 ---- 2019-3-8   ------------
 
 -- UPDATE
 UPDATE ORDERS_TBL SET QTY = 1 WHERE ORD_NUM ='23A16'; --更新一行
 UPDATE ORDERS_TBL SET QTY = 1; --更新表中所有的数据
 select * from ORDERS_TBL;
 
 ----2019-3-13--
 --更新多列
 UPDATE ORDERS_TBL SET QTY = 1, CUST_ID = '221' WHERE ORD_NUM ='23A16';
 
 --删除
 delete from ORDERS_TBL where ORD_NUM='23A16';
 
 --第五章课后题
-- 5.7.2
INSERT INTO PRODUCTS_TBL (PROD_ID,PROD_DESC,COST) 
VALUES('301','FIREMEN COSTUME',24.99); 
INSERT INTO PRODUCTS_TBL (PROD_ID,PROD_DESC,COST) 
VALUES('302','POLICEMAN COSTUME',24.99);
INSERT INTO PRODUCTS_TBL (PROD_ID,PROD_DESC,COST) 
VALUES('303','KIDDIE GRAB BAG',4.99);  
 
 SELECT * FROM PRODUCTS_TBL;
 
 -- 修改两种服装的价格 301 302 变成29.99
update PRODUCTS_TBL set cost=29.99 where PROD_ID = '301' AND  PROD_ID = '302';
update PRODUCTS_TBL set cost=29.99 where PROD_ID in('301','302');

--为了确保删除内容正确 可以先执行一个SELECT语句  
DELETE FROM PRODUCTS_TBL WHERE PROD_ID = '301';
--这样也可以删除 不过只能删除满足条件的一列
DELETE FROM PRODUCTS_TBL WHERE COST = '24.99' AND ROWNUM =1;
 