--DATE：2019-3-5 谢龙 第五章SQL
SELECT * FROM PRODUCTS_TBL;

DROP TABLE "HR"."products_tmp";

--一开始没有表
SELECT * FROM PRODUCTS_TMP;

--建表
CREATE TABLE products_tmp
  (
    "PROD_ID"   VARCHAR2(10 BYTE) NOT NULL ENABLE,
    "PROD_DESC" VARCHAR2(40 BYTE) NOT NULL ENABLE,
    "COST"      NUMBER(6,2) NOT NULL ENABLE,
    PRIMARY KEY ("PROD_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "USERS" ENABLE
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "USERS" ;
--插入PRODUCTS_TBL全部数据
INSERT INTO PRODUCTS_TMP SELECT * FROM PRODUCTS_TBL ;
--看到了数据
SELECT * FROM PRODUCTS_TMP;

----插入空值
  INSERT INTO ORDERS_TBL (ORD_NUM, CUST_ID, PROD_ID, QTY, ORD_DATE) VALUES ('23A16','109', '7725',2, NULL);
  
commit;