
-- date:2019-3-20 sql入门经典第六章 

select * from products_tmp;

DELETE FROM products_tmp WHERE COST<14;
--提交
commit;

SELECT * FROM products_tmp;
--更新 29.99-39.99
UPDATE products_tmp SET COST=39.99 WHERE prod_id='11235';
--再次查询-39.99
SELECT * FROM products_tmp;
--回滚回之前的状态 29.99
ROLLBACK;
--再次查询
SELECT * FROM products_tmp;

--事务属性
--读写
SET TRANSACTION READ WRITE;
--只读
SET TRANSACTION READ ONLY;

--课后题
SELECT * FROM CUSTOMER_TBL;
-- 第1题
INSERT INTO CUSTOMER_TBL VALUES(615,'FRED WOLF','109 MEMORY LANE','PLAINFIELD','IN','46113','3175555555',NULL);
INSERT INTO CUSTOMER_TBL VALUES(559,'RITA THOMPSON','125 PEACHTREE','INDIANAPOLIS','IN','46248','3171111111',NULL); 
INSERT INTO CUSTOMER_TBL VALUES(715,'BOB DIGGLER','1102 HUNTINGTON ST','SHELBY','IN','4123','3172222222',NULL); 
SAVEPOINT SP1;
UPDATE CUSTOMER_TBL SET CUST_NAME='FRED_WOLF' WHERE CUST_ID='559';
UPDATE CUSTOMER_TBL SET CUST_ADDRESS='APT C 4556 WATERWAY' WHERE CUST_ID='615';
UPDATE CUSTOMER_TBL SET CUST_CITY='CHICAGO' WHERE CUST_ID='715'; 
ROLLBACK ;

SELECT * FROM CUSTOMER_TBL;

-- 第2题
SELECT * FROM CUSTOMER_TBL;
UPDATE CUSTOMER_TBL SET CUST_NAME='FRED_WOLF' WHERE CUST_ID='559';
UPDATE CUSTOMER_TBL SET CUST_ADDRESS='APT C 4556 WATERWAY' WHERE CUST_ID='615';
UPDATE CUSTOMER_TBL SET CUST_CITY='CHICAGO' WHERE CUST_ID='715';
SAVEPOINT SP1;
DELETE FROM CUSTOMER_TBL WHERE CUST_ID='615';
DELETE FROM CUSTOMER_TBL WHERE CUST_ID='559';
DELETE FROM CUSTOMER_TBL WHERE CUST_ID='615';
COMMIT;
ROLLBACK; -- 回退无效 commit以后回退无效
ROLLBACK TO SP1 ;-- SQL 错误: ORA-01086: 从未在此会话中创建保存点 'SP1' 或者该保存点无效
