---DATE：2019-05-24  Author:xielong Email:cnxielong@gamail.com 第十一章 SQL入门经典
SELECT CITY,STATE FROM EMPLOYEE_TBL;
select city || ' '|| state from employee_tbl;

SELECT CITY FROM EMPLOYEE_TBL; 
SELECT TRANSLATE(CITY,'IND','ABC') FROM EMPLOYEE_TBL;

--select * from jobs;
--SELECT * FROM EMPLOYEE_TBL;
--DELETE FROM EMPLOYEE_TBL WHERE EMP_ID ='111111111';
--ROLLBACK;

--ALTER TABLE JOBS ADD TESTCO VARCHAR2(100 CHAR);
--ALTER TABLE JOBS drop column TESTCO;



