--DATE：2019-05-22  Author:谢龙 第十章SQL
select sum(salary) from employee_pay_tbl;

select sum(salary) from employee_pay_tbl group by salary;

SELECT CITY FROM EMPLOYEE_TBL;

SELECT CITY,COUNT(*) FROM EMPLOYEE_TBL GROUP BY CITY;

-- 内连接
SELECT CITY, ZIP,AVG(PAY_RATE),AVG(SALARY) FROM EMPLOYEE_TBL E INNER JOIN EMPLOYEE_PAY_TBL P
on E.EMP_ID=P.EMP_ID group by city,zip order by city,zip;

--使用 RULLUP分组
SELECT CITY, ZIP,AVG(PAY_RATE),AVG(SALARY) FROM EMPLOYEE_TBL E INNER JOIN EMPLOYEE_PAY_TBL P
on E.EMP_ID=P.EMP_ID group by ROLLUP(city,zip);

SELECT DATE_HIRE,SUM(SALARY) FROM EMPLOYEE_PAY_TBL GROUP BY DATE_HIRE HAVING SUM(SALARY)>200;


--课后题答案
SELECT CITY FROM EMPLOYEE_TBL;
SELECT CITY,COUNT(*) FROM EMPLOYEE_TBL GROUP BY CITY;

SELECT CITY,COUNT(*) FROM EMPLOYEE_TBL GROUP BY CITY HAVING COUNT(*)>1;

SELECT CITY,COUNT(*) FROM EMPLOYEE_TBL GROUP BY CITY HAVING COUNT(*)>-1 ORDER BY count(*) desc ;

--第五题
select * from EMPLOYEE_PAY_RATE;
